#!/bin/bash
nohup python apiserver/manage.py runserver 0.0.0.0:8000 1>/tmp/log 2>&1 &
echo $! > /tmp/api.pid
nohup node gameserver/server/main.js 1>/tmp/log 2>&1 &
echo $! > /tmp/gameserver.pid
cd client
nohup  npm start 1>/tmp/log 2>&1 &
echo $! > /tmp/devserver.pid
tail -f /tmp/log
