# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
        ('main', '0002_auto_20170223_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodes.GameNode'),
        ),
        migrations.AlterField(
            model_name='player',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=128),
        ),
    ]
