# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170224_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ready',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='creator',
            field=models.BooleanField(default=False),
        ),
    ]
