# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import services.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('last_modified', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('host', models.CharField(max_length=64)),
                ('port', models.CharField(max_length=5)),
                ('available', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('token', models.CharField(default=uuid.uuid4, max_length=128)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, services.models.BaseModelMixin),
        ),
    ]
