# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_chatnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatnode',
            name='node_tag',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='gamenode',
            name='node_tag',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
